# ==============================================================================
# Powerlevel10k Configuration - Catppuccin Mocha Theme
# Generated by Powerlevel10k configuration wizard
# ==============================================================================

'builtin' 'local' '-a' 'p10k_config_opts'
[[ ! -o 'aliases'         ]] || p10k_config_opts+=('aliases')
[[ ! -o 'sh_glob'         ]] || p10k_config_opts+=('sh_glob')
[[ ! -o 'no_brace_expand' ]] || p10k_config_opts+=('no_brace_expand')
'builtin' 'setopt' 'no_aliases' 'no_sh_glob' 'brace_expand'

() {
  emulate -L zsh -o extended_glob

  # Unset all configuration options
  unset -m '(POWERLEVEL9K_*|DEFAULT_USER)~POWERLEVEL9K_GITSTATUS_DIR'

  # Zsh >= 5.1 is required
  [[ $ZSH_VERSION == (5.<1->*|<6->.*) ]] || return

  # ==============================================================================
  # Catppuccin Mocha Color Palette
  # ==============================================================================
  local rosewater='#f5e0dc'
  local flamingo='#f2cdcd'
  local pink='#f5c2e7'
  local mauve='#cba6f7'
  local red='#f38ba8'
  local maroon='#eba0ac'
  local peach='#fab387'
  local yellow='#f9e2af'
  local green='#a6e3a1'
  local teal='#94e2d5'
  local sky='#89dceb'
  local sapphire='#74c7ec'
  local blue='#89b4fa'
  local lavender='#b4befe'
  local text='#cdd6f4'
  local subtext1='#bac2de'
  local subtext0='#a6adc8'
  local overlay2='#9399b2'
  local overlay1='#7f849c'
  local overlay0='#6c7086'
  local surface2='#585b70'
  local surface1='#45475a'
  local surface0='#313244'
  local base='#1e1e2e'
  local mantle='#181825'
  local crust='#11111b'

  # ==============================================================================
  # Prompt Style
  # ==============================================================================
  
  # The prompt style
  typeset -g POWERLEVEL9K_MODE='nerdfont-v3'
  typeset -g POWERLEVEL9K_ICON_PADDING=moderate

  # Prompt segments
  typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
    os_icon
    dir
    vcs
    prompt_char
  )

  typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(
    status
    command_execution_time
    background_jobs
    node_version
    python
    go_version
    rust_version
    context
    time
  )

  # ==============================================================================
  # Basic Settings
  # ==============================================================================
  
  typeset -g POWERLEVEL9K_BACKGROUND=
  typeset -g POWERLEVEL9K_{LEFT,RIGHT}_{LEFT,RIGHT}_WHITESPACE=
  typeset -g POWERLEVEL9K_{LEFT,RIGHT}_SUBSEGMENT_SEPARATOR=' '
  typeset -g POWERLEVEL9K_{LEFT,RIGHT}_SEGMENT_SEPARATOR=
  typeset -g POWERLEVEL9K_VISUAL_IDENTIFIER_EXPANSION=

  # Transient prompt
  typeset -g POWERLEVEL9K_TRANSIENT_PROMPT=off
  typeset -g POWERLEVEL9K_INSTANT_PROMPT=verbose

  # ==============================================================================
  # OS Icon
  # ==============================================================================
  typeset -g POWERLEVEL9K_OS_ICON_FOREGROUND=$blue
  typeset -g POWERLEVEL9K_OS_ICON_CONTENT_EXPANSION='${P9K_CONTENT}'

  # ==============================================================================
  # Directory
  # ==============================================================================
  typeset -g POWERLEVEL9K_DIR_FOREGROUND=$lavender
  typeset -g POWERLEVEL9K_DIR_SHORTENED_FOREGROUND=$overlay1
  typeset -g POWERLEVEL9K_DIR_ANCHOR_FOREGROUND=$lavender
  typeset -g POWERLEVEL9K_DIR_ANCHOR_BOLD=true

  typeset -g POWERLEVEL9K_SHORTEN_STRATEGY=truncate_to_unique
  typeset -g POWERLEVEL9K_SHORTEN_DELIMITER=
  typeset -g POWERLEVEL9K_DIR_TRUNCATE_BEFORE_MARKER=false
  typeset -g POWERLEVEL9K_SHORTEN_DIR_LENGTH=1
  typeset -g POWERLEVEL9K_DIR_MAX_LENGTH=80
  typeset -g POWERLEVEL9K_DIR_MIN_COMMAND_COLUMNS=40
  typeset -g POWERLEVEL9K_DIR_MIN_COMMAND_COLUMNS_PCT=50
  typeset -g POWERLEVEL9K_DIR_HYPERLINK=false

  typeset -g POWERLEVEL9K_DIR_SHOW_WRITABLE=v3

  # ==============================================================================
  # VCS (Git)
  # ==============================================================================
  typeset -g POWERLEVEL9K_VCS_BRANCH_ICON=' '
  typeset -g POWERLEVEL9K_VCS_UNTRACKED_ICON='?'

  # Clean
  typeset -g POWERLEVEL9K_VCS_CLEAN_FOREGROUND=$green
  
  # Modified
  typeset -g POWERLEVEL9K_VCS_MODIFIED_FOREGROUND=$yellow
  
  # Untracked
  typeset -g POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND=$peach

  typeset -g POWERLEVEL9K_VCS_BACKENDS=(git)

  # ==============================================================================
  # Prompt Character
  # ==============================================================================
  typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_{VIINS,VICMD,VIVIS,VIOWR}_FOREGROUND=$green
  typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_{VIINS,VICMD,VIVIS,VIOWR}_FOREGROUND=$red
  typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIINS_CONTENT_EXPANSION='❯'
  typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VICMD_CONTENT_EXPANSION='❮'
  typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIVIS_CONTENT_EXPANSION='V'
  typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIOWR_CONTENT_EXPANSION='▶'
  typeset -g POWERLEVEL9K_PROMPT_CHAR_OVERWRITE_STATE=true
  typeset -g POWERLEVEL9K_PROMPT_CHAR_LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL=''
  typeset -g POWERLEVEL9K_PROMPT_CHAR_LEFT_PROMPT_FIRST_SEGMENT_START_SYMBOL=

  # ==============================================================================
  # Status
  # ==============================================================================
  typeset -g POWERLEVEL9K_STATUS_EXTENDED_STATES=true
  typeset -g POWERLEVEL9K_STATUS_OK=false
  typeset -g POWERLEVEL9K_STATUS_OK_FOREGROUND=$green
  typeset -g POWERLEVEL9K_STATUS_OK_VISUAL_IDENTIFIER_EXPANSION='✔'

  typeset -g POWERLEVEL9K_STATUS_OK_PIPE=true
  typeset -g POWERLEVEL9K_STATUS_OK_PIPE_FOREGROUND=$green
  typeset -g POWERLEVEL9K_STATUS_OK_PIPE_VISUAL_IDENTIFIER_EXPANSION='✔'

  typeset -g POWERLEVEL9K_STATUS_ERROR=true
  typeset -g POWERLEVEL9K_STATUS_ERROR_FOREGROUND=$red
  typeset -g POWERLEVEL9K_STATUS_ERROR_VISUAL_IDENTIFIER_EXPANSION='✘'

  typeset -g POWERLEVEL9K_STATUS_ERROR_SIGNAL=true
  typeset -g POWERLEVEL9K_STATUS_ERROR_SIGNAL_FOREGROUND=$red
  typeset -g POWERLEVEL9K_STATUS_VERBOSE_SIGNAME=false
  typeset -g POWERLEVEL9K_STATUS_ERROR_SIGNAL_VISUAL_IDENTIFIER_EXPANSION='✘'

  typeset -g POWERLEVEL9K_STATUS_ERROR_PIPE=true
  typeset -g POWERLEVEL9K_STATUS_ERROR_PIPE_FOREGROUND=$red
  typeset -g POWERLEVEL9K_STATUS_ERROR_PIPE_VISUAL_IDENTIFIER_EXPANSION='✘'

  # ==============================================================================
  # Command Execution Time
  # ==============================================================================
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=2
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_PRECISION=0
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND=$yellow
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FORMAT='d h m s'
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_VISUAL_IDENTIFIER_EXPANSION=
  
  # ==============================================================================
  # Background Jobs
  # ==============================================================================
  typeset -g POWERLEVEL9K_BACKGROUND_JOBS_VERBOSE=false
  typeset -g POWERLEVEL9K_BACKGROUND_JOBS_FOREGROUND=$mauve
  typeset -g POWERLEVEL9K_BACKGROUND_JOBS_VISUAL_IDENTIFIER_EXPANSION='⚙'

  # ==============================================================================
  # Languages
  # ==============================================================================
  
  # Node.js
  typeset -g POWERLEVEL9K_NODE_VERSION_FOREGROUND=$green
  typeset -g POWERLEVEL9K_NODE_VERSION_VISUAL_IDENTIFIER_EXPANSION=' '
  typeset -g POWERLEVEL9K_NODE_VERSION_PROJECT_ONLY=true

  # Python
  typeset -g POWERLEVEL9K_PYTHON_FOREGROUND=$yellow
  typeset -g POWERLEVEL9K_PYTHON_VISUAL_IDENTIFIER_EXPANSION=' '

  # Go
  typeset -g POWERLEVEL9K_GO_VERSION_FOREGROUND=$sky
  typeset -g POWERLEVEL9K_GO_VERSION_VISUAL_IDENTIFIER_EXPANSION=' '
  typeset -g POWERLEVEL9K_GO_VERSION_PROJECT_ONLY=true

  # Rust
  typeset -g POWERLEVEL9K_RUST_VERSION_FOREGROUND=$peach
  typeset -g POWERLEVEL9K_RUST_VERSION_VISUAL_IDENTIFIER_EXPANSION=' '
  typeset -g POWERLEVEL9K_RUST_VERSION_PROJECT_ONLY=true

  # ==============================================================================
  # Context
  # ==============================================================================
  typeset -g POWERLEVEL9K_CONTEXT_ROOT_FOREGROUND=$red
  typeset -g POWERLEVEL9K_CONTEXT_{REMOTE,REMOTE_SUDO}_FOREGROUND=$yellow
  typeset -g POWERLEVEL9K_CONTEXT_FOREGROUND=$text
  typeset -g POWERLEVEL9K_CONTEXT_ROOT_TEMPLATE='%n@%m'
  typeset -g POWERLEVEL9K_CONTEXT_{REMOTE,REMOTE_SUDO}_TEMPLATE='%n@%m'
  typeset -g POWERLEVEL9K_CONTEXT_TEMPLATE=
  typeset -g POWERLEVEL9K_CONTEXT_{DEFAULT,SUDO}_{CONTENT,VISUAL_IDENTIFIER}_EXPANSION=

  # ==============================================================================
  # Time
  # ==============================================================================
  typeset -g POWERLEVEL9K_TIME_FOREGROUND=$subtext0
  typeset -g POWERLEVEL9K_TIME_FORMAT='%D{%H:%M}'
  typeset -g POWERLEVEL9K_TIME_UPDATE_ON_COMMAND=false
  typeset -g POWERLEVEL9K_TIME_VISUAL_IDENTIFIER_EXPANSION=

  # ==============================================================================
  # Finalizing
  # ==============================================================================
  (( ${#p10k_config_opts} )) && setopt ${p10k_config_opts[@]}
  'builtin' 'unset' 'p10k_config_opts'
}
